### ISSUE TITLE
Problem installing with Ruby-1.9.3-p327

### ISSUE THREAD

**Issue by ncancelliere** [cldwalker/debugger-linecache#2]
I am not sure if this is a debugger-ruby_core_source issues or debuger-linecache, but when I try to install it under RVM with ruby-1.9.3-p327 I get the following (it installs perfectly fine with ruby-1.9.3-p194):

```
nicholas@neptune:~/$ gem install debugger-linecache -v '1.1.2' -- --with-ruby-include=/Users/nicholas/.rvm/src/ruby-1.9.3-p327
Fetching: debugger-ruby_core_source-1.1.5.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing debugger-linecache:
    ERROR: Failed to build gem native extension.

        /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/bin/ruby extconf.rb --with-ruby-include=/Users/nicholas/.rvm/src/ruby-1.9.3-p327
checking for vm_core.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/bin/ruby
    --with-ruby-dir
    --without-ruby-dir
    --with-ruby-include=${ruby-dir}/include
    --with-ruby-lib
    --without-ruby-lib=${ruby-dir}/lib
/Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:369:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:494:in `try_cpp'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:919:in `block in have_header'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:778:in `block in checking_for'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:272:in `block (2 levels) in postpone'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:242:in `open'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:272:in `block in postpone'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:242:in `open'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:268:in `postpone'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:777:in `checking_for'
    from /Users/nicholas/.rvm/rubies/ruby-1.9.3-p327/lib/ruby/1.9.1/mkmf.rb:918:in `have_header'
    from extconf.rb:9:in `block in <main>'
    from /Users/nicholas/.rvm/gems/ruby-1.9.3-p327@whiteglove_api_client/gems/debugger-ruby_core_source-1.1.5/lib/debugger/ruby_core_source.rb:17:in `call'
    from /Users/nicholas/.rvm/gems/ruby-1.9.3-p327@whiteglove_api_client/gems/debugger-ruby_core_source-1.1.5/lib/debugger/ruby_core_source.rb:17:in `create_makefile_with_core'
    from extconf.rb:13:in `<main>'
```

**Comment by marsadle** [comment]
You need to run `gem install debugger-ruby_core_source` first. This will resolve the dependency issues.

**Comment by cldwalker** [comment]
Strange. debugger-ruby_core_source 1.1.5 includes headers for 1.9.3-p327. Could you uninstall all debugger gems and install the latest debugger? If that doesn't work include your installed debugger gems with `gem list debugger`

**Comment by cldwalker** [comment]
Closing due to no response.
